# Generated by Django 5.0.6 on 2024-06-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catogary',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcatogary',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/images'),
        ),
    ]
