# Generated by Django 5.0.6 on 2024-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_rename_catogary_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=110)),
                ('address', models.CharField(max_length=110)),
                ('city', models.CharField(max_length=110)),
                ('state', models.CharField(max_length=110)),
                ('zip_code', models.CharField(max_length=110)),
                ('phone', models.CharField(max_length=110)),
            ],
        ),
    ]
