# Generated by Django 5.2.6 on 2026-01-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_remove_product_product_id_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
